### ISSUE TITLE
TypeError: window.getScreenDetails is not a function

### ISSUE THREAD

**Issue by liudonghua123** [sonkkeli/borderless#2]
Hi, I tried the steps on https://github.com/sonkkeli/borderless/tree/main/demo-app, but when I click `Grant` Button, it did nothing, and I got some errors on console of devtools. 

Reproduce steps:

1. git clone https://github.com/sonkkeli/borderless.git
2. cd borderless\demo-app\
3. npm i
4. npm run serve
5. open http://MY_HOST_IP:8080 on chrome 116

![image](https://github.com/sonkkeli/borderless/assets/2276718/9de90330-1fc1-488b-b6a1-d4b075540a66)

**Comment by liudonghua123** [comment]
I tried to install as a PWA app, then this error disappeared. However, the title bar of the app has not changed as expected.

![image](https://github.com/sonkkeli/borderless/assets/2276718/e01bc38d-0a14-4cef-b11a-275340281b7c)

**Comment by sonkkeli** [comment]
It looks like you are running it with Mac. For now this is only supported on ChromeOS / Linux (behind a flag).
